# Camera configuration using MnDOT snapshot endpoints.
# Each snapshot is polled every 10 seconds but processed only once per unique frame.

# I-94 Hudson Rd WB @ 4th St
- camera_id: "C30248"
  name: "I-94: Hudson Rd WB @ 4th St"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30248"
  corridor: "I-94"
  direction: "WB"
  poll_interval_sec: 10

# I-94 Hudson Rd WB @ 19th St
- camera_id: "C30250"
  name: "I-94: Hudson Rd WB @ 19th St"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30250"
  corridor: "I-94"
  direction: "WB"
  poll_interval_sec: 10

# I-94 EB @ T.H.120 (Century Ave)
- camera_id: "C860"
  name: "I-94: EB @ T.H.120 (Century Ave)"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C860"
  corridor: "I-94"
  direction: "EB"
  poll_interval_sec: 10

# I-94 WB east of T.H.120
- camera_id: "C30251"
  name: "I-94: WB east of T.H.120"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30251"
  corridor: "I-94"
  direction: "WB"
  poll_interval_sec: 10

# I-94 WB @ Ideal Ave N
- camera_id: "C30285"
  name: "I-94: WB @ Ideal Ave N"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30285"
  corridor: "I-94"
  direction: "WB"
  poll_interval_sec: 10

# # I-94 EB @ Heggen St
# - camera_id: "C870"
#   name: "I-94: EB @ Heggen St"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C870"
#   corridor: "I-94"
#   direction: "EB"
#   poll_interval_sec: 10

# # I-94 WB @ T.H.95 (St Croix Trl)
# - camera_id: "C869"
#   name: "I-94: WB @ T.H.95 (St Croix Trl)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C869"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10

# # I-94 WB W of T.H.95 (St Croix Trl)
# - camera_id: "C30289"
#   name: "I-94: WB W of T.H.95 (St Croix Trl)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30289"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10

# # I-94 WB @ Co Rd 21 (Stagecoach Trl)
# - camera_id: "C868"
#   name: "I-94: WB @ Co Rd 21 (Stagecoach Trl)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C868"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10

# # I-94 EB W of Co Rd 21 (Stagecoach Trl)
# - camera_id: "C30288"
#   name: "I-94: EB W of Co Rd 21 (Stagecoach Trl)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30288"
#   corridor: "I-94"
#   direction: "EB"
#   poll_interval_sec: 10

# # I-94 WB @ St. Croix Rest Area
# - camera_id: "C867"
#   name: "I-94: WB @ St. Croix Rest Area"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C867"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10

# # I-94 EB @ St. Croix Rest Area
# - camera_id: "C30040"
#   name: "I-94: EB @ St. Croix Rest Area"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30040"
#   corridor: "I-94"
#   direction: "EB"
#   poll_interval_sec: 10

# # I-94 EB E of Co Rd 71 (E of Neal Ave)
# - camera_id: "C30287"
#   name: "I-94: EB E of Co Rd 71 (E of Neal Ave)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30287"
#   corridor: "I-94"
#   direction: "EB"
#   poll_interval_sec: 10

# # I-94 WB @ Co Rd 71 (Neal Ave)
# - camera_id: "C866"
#   name: "I-94: WB @ Co Rd 71 (Neal Ave)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C866"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10

# # I-94 WB @ Co Rd 17B (Lake Elmo Ave)
# - camera_id: "C864"
#   name: "I-94: WB @ Co Rd 17B (Lake Elmo Ave)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C864"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10

# # I-94 WB @ Co Rd 19 (Keats Ave/Woodbury Dr)
# - camera_id: "C863"
#   name: "I-94: WB @ Co Rd 19 (Keats Ave/Woodbury Dr)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C863"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10

# # I-94 WB E of Radio Dr
# - camera_id: "C30286"
#   name: "I-94: WB E of Radio Dr"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30286"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10

# # I-94 EB @ Co Rd 13 (Inwood Ave/Radio Dr)
# - camera_id: "C862"
#   name: "I-94: EB @ Co Rd 13 (Inwood Ave/Radio Dr)"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C862"
#   corridor: "I-94"
#   direction: "EB"
#   poll_interval_sec: 10

# # Hudson Rd WB @ 8th St
# - camera_id: "C30249"
#   name: "I-94: Hudson Rd WB @ 8th St"
#   snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30249"
#   corridor: "I-94"
#   direction: "WB"
#   poll_interval_sec: 10
